import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer'
import { todayISO } from '../utils/date'

// Heebo תומך גם בעברית וגם בלטינית — נחוץ כי שדות כמו מדינת מוצא/סוג סחורה/איש קשר
// מוזנים לעיתים בעברית, וגופני ה-PDF המובנים (Helvetica וכו') לא כוללים גליפים עבריים.
Font.register({
  family: 'Heebo',
  fonts: [
    { src: '/fonts/Heebo-Regular.ttf', fontWeight: 400 },
    { src: '/fonts/Heebo-Bold.ttf', fontWeight: 700 },
  ],
})

export interface RfqPdfData {
  // מזהה ה-RFQ (RFQ-2026-014). מופיע גם בנושא המייל וגם ברשומה, ומשמש לזיהוי תשובות חוזרות.
  rfqReference: string
  name: string
  originCountry: string
  originCity: string
  readyDate: string
  supplierName: string
  pickupAddress: string
  contactPerson: string
  contactEmail: string
  contactPhone: string
  cartons: string
  weight: string
  dimensions: string
  onPallet: boolean
  palletCount: string
  goodsType: string
  isDangerousGoods: boolean
}

export interface RfqPdfDocumentFile {
  category: string
  fileName: string
}

const EMPTY = '-'
const fmt = (v: string) => (v.trim() ? v.trim() : EMPTY)

const styles = StyleSheet.create({
  page: { fontFamily: 'Heebo', fontSize: 10, color: '#292524', padding: 40 },
  title: { fontSize: 18, fontWeight: 700, marginBottom: 2 },
  subtitle: { fontSize: 9, color: '#78716c', marginBottom: 20 },
  metaRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24, paddingBottom: 12, borderBottom: '1 solid #e7e5e4' },
  metaLabel: { fontSize: 8, color: '#a8a29e', marginBottom: 2 },
  metaValue: { fontSize: 11, fontWeight: 700 },
  section: { marginBottom: 18 },
  sectionTitle: { fontSize: 11, fontWeight: 700, marginBottom: 8, color: '#78350f' },
  row: { flexDirection: 'row', marginBottom: 6 },
  col: { flex: 1 },
  label: { fontSize: 8, color: '#a8a29e', marginBottom: 1 },
  value: { fontSize: 10.5, color: '#292524' },
  docsList: { marginTop: 2 },
  docRow: { flexDirection: 'row', marginBottom: 4 },
  docCategory: { fontSize: 10, fontWeight: 700, width: 140 },
  docFiles: { fontSize: 10, color: '#44403c', flex: 1 },
  docFilesEmpty: { fontSize: 10, color: '#a8a29e', flex: 1 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 8, color: '#a8a29e', borderTop: '1 solid #e7e5e4', paddingTop: 8 },
})

function Field({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.col}>
      <Text style={styles.label}>{label}</Text>
      <Text style={styles.value}>{value}</Text>
    </View>
  )
}

export function RfqPdfDocument({ data, documents }: { data: RfqPdfData; documents: RfqPdfDocumentFile[] }) {
  const origin = [data.originCity, data.originCountry].filter((v) => v.trim()).join(', ') || EMPTY
  const weight = data.weight.trim() ? `${data.weight.trim()} kg` : EMPTY
  const pallets = data.onPallet ? fmt(data.palletCount) !== EMPTY ? data.palletCount.trim() : 'Yes' : 'No'
  const categories = ['Commercial Invoice', 'Packing List', 'MSDS / SDS', 'Other document']

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Request for Shipping Quotation</Text>
        <Text style={styles.subtitle}>Generated by Life Control Center</Text>

        <View style={styles.metaRow}>
          <View>
            <Text style={styles.metaLabel}>Date</Text>
            <Text style={styles.metaValue}>{todayISO()}</Text>
          </View>
          <View>
            <Text style={styles.metaLabel}>RFQ Reference</Text>
            <Text style={styles.metaValue}>{fmt(data.rfqReference)}</Text>
          </View>
          <View>
            <Text style={styles.metaLabel}>Shipment</Text>
            <Text style={styles.metaValue}>{fmt(data.name)}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Shipment</Text>
          <View style={styles.row}>
            <Field label="Origin" value={origin} />
            <Field label="Ready date" value={fmt(data.readyDate)} />
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Pickup / Supplier</Text>
          <View style={styles.row}>
            <Field label="Supplier / Company" value={fmt(data.supplierName)} />
            <Field label="Pickup address" value={fmt(data.pickupAddress)} />
          </View>
          <View style={styles.row}>
            <Field label="Contact person" value={fmt(data.contactPerson)} />
            <Field label="Email" value={fmt(data.contactEmail)} />
            <Field label="Phone" value={fmt(data.contactPhone)} />
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Cargo</Text>
          <View style={styles.row}>
            <Field label="Cargo type" value={fmt(data.goodsType)} />
            <Field label="Number of cartons" value={fmt(data.cartons)} />
            <Field label="Total weight" value={weight} />
          </View>
          <View style={styles.row}>
            {data.dimensions.trim() && <Field label="Dimensions / Volume" value={data.dimensions.trim()} />}
            <Field label="Pallets" value={pallets} />
            <Field label="Dangerous Goods (DG)" value={data.isDangerousGoods ? 'Yes' : 'No'} />
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Attached Documents</Text>
          <View style={styles.docsList}>
            {categories.map((cat) => {
              const files = documents.filter((d) => d.category === cat)
              return (
                <View key={cat} style={styles.docRow}>
                  <Text style={styles.docCategory}>{cat}</Text>
                  {files.length > 0 ? (
                    <Text style={styles.docFiles}>{files.map((f) => f.fileName).join(', ')}</Text>
                  ) : (
                    <Text style={styles.docFilesEmpty}>Not attached</Text>
                  )}
                </View>
              )
            })}
          </View>
        </View>

        <Text style={styles.footer}>Please send your quotation at your earliest convenience.</Text>
      </Page>
    </Document>
  )
}
